version: '3'
services:
  competition_service:
    build: ./competition_service
    ports:
      - "5001:5001"
    env_file:
      - ./competition_service/.env
    container_name: competition_service
    depends_on:
      - postgres_competition
    links:
      - postgres_competition

  user_management_service:
    build: ./user_management_service
    ports:
      - "5000:5000"
    env_file:
      - ./user_management_service/.env
    container_name: user_management_service
    depends_on:
      - postgres_user_management
    links:
      - postgres_user_management

  postgres_user_management:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: UserManagement
    ports:
      - "5434:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    
  postgres_competition:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: CompetitionDB
    ports:
      - "5435:5432"
    volumes:
      - postgres_competition_data:/var/lib/postgresql/data

volumes:
  postgres_user_data:
  postgres_competition_data: